// Random C code generated by AI Assistant
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    int i = 0;
    char *str = "Hello, world!";
    printf("The string is: %s\n", str);
    while (i < strlen(str)) {
        if (str[i] == 'H') {
            printf("Found the letter H at position %d\n", i + 1);
        } else {
            i++;
        }
    }
    return 0;
}
